<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>VisionMaven.Modules.Model</RootNamespace>
    <AssemblyName>VisionMaven.Modules.Model</AssemblyName>
    <Description>模型：模型库管理、导入删除、推理设置与测试推理。</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" />
    <PackageReference Include="HandyControl" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisionMaven.Core\VisionMaven.Core.csproj" />
    <ProjectReference Include="..\VisionMaven.Modules.Shared\VisionMaven.Modules.Shared.csproj" />
  </ItemGroup>

</Project>
